---
- hosts: all
  remote_user: vagrant
  become_user: root
  become: yes
  vars:
    config_system_locale: 'de_DE.UTF-8'
    config_system_timezone: 'Europe/Berlin'
    config_keyboard_layout: 'de'
    ehacking_docker: "main"
    config_dir: "{{ playbook_dir }}/../config"
    vm_user: "student"
  roles:
    - ubuntu
    - common
    - firefox
    - chromium
    - apache
    - burpsuite
    - ehacking-docker
    - vscode

  tasks:
    - name: Install brono REST client (only available on x86)
      include_role:
          name: bruno
      when: ansible_architecture == 'x86_64'